### ISSUE TITLE
[dev] [sequential] not showing sense number as superscript

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#143] opened 2019-08-08 00:11 UTC
annotating north, chose north%n and sense 4, finish. The buffer does not show the superscript 4.

**Comment by arademaker** [comment] 2019-08-09 17:18
I can't reproduce the error anymore.

**Comment by arademaker** [comment] 2019-08-09 18:23
in the sequential mode the problem appears.

**Comment by odanoburu** [comment] 2019-08-15 16:47
> in the sequential mode the problem appears.

this is by design, actually. i don't think we reached on a consensus on what to do here.. just showing an index doesn't make much sense in sequential mode, ref #99

**Comment by odanoburu** [comment] 2019-08-16 14:30
closing this in favor of #145

**Closed by odanoburu** 2019-08-16 14:30 UTC
