### ISSUE TITLE
touch.py tokenization bug?

### ISSUE THREAD

**Issue by alexandretessarollo** [own-pt/sensetion.el#135] opened 2019-08-05 17:03 UTC
Touch is causing some text losses. I'm inputing a sent file (one sentence per line) and not all sentences are coming out. Apparently, in some cases, it also changes the order of the sentences.

**Comment by hmuniz** [comment] 2019-08-05 18:36
An example of a file that occurs a problem:
```
The oil and gas industry uses wireline logging to obtain a continuous record of a formation's rock properties.
Wireline logging can be defined as being "The acquisition and analysis of geophysical data performed as a function of well bore depth, together with the provision of related services."
Note that "wireline logging" and "mud logging" are not the same, yet are closely linked through the integration of the data sets.
The measurements are made referenced to "TAH" - True Along Hole depth: these and the associated analysis can then be used to infer further properties, such as hydrocarbon saturation and formation pressure, and to make further drilling and production decisions.
```
The error:
```python
Traceback (most recent call last):
  File "touch.py", line 55, in <module>
    main()
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "touch.py", line 50, in main
    for sent_json in sents:
  File "touch.py", line 39, in go_doc
    yield to_json(go_sent(line.rstrip('\n'), sent_id, doc_id, tkz))
  File "touch.py", line 26, in go_sent
    latt = tkz.tokenize(sent)
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/delphin/repp.py", line 466, in tokenize
    return self.group.tokenize(s, pattern=pattern, active=active)
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/delphin/repp.py", line 93, in tokenize
    res = self.apply(s, active=active)
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/delphin/repp.py", line 72, in apply
    for step in self.trace(s, active=active):
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/delphin/repp.py", line 86, in trace
    startmap = _mergemap(startmap, step.startmap)
  File "/home/hmuniz/.virtualenvs/test/lib/python3.7/site-packages/delphin/repp.py", line 481, in _mergemap
    merged[i] = shift + map1[i + shift]
IndexError: array index out of range
```
The problem is with sentences that end with `"`. The following command voids the problem:
```sh
sed -i 's/"$/"./' *.sent
```
But it is not solved, I don't know yet if the error it is caused by the REPP pet definition or pydelphin's REPP  implementation.

**Comment by arademaker** [comment] 2019-08-05 19:47
Using `ace -E ...` shows that it seems to be a problem of https://github.com/delph-in/pydelphin.

**Comment by odanoburu** [comment] 2019-08-15 17:16
@alexandretessarollo can you test if this still happens with the new version of pydelphin and if not open an issue there?

**Comment by odanoburu** [comment] 2019-08-15 18:23
@hmuniz told me it doesn't work in the new version either, so just open the issue with a minimal example of the error? @alexandretessarollo

**Comment by arademaker** [comment] 2019-08-15 20:13
See https://github.com/delph-in/pydelphin/issues/250

**Comment by arademaker** [comment] 2019-08-15 20:18
why are you closing this?

**Comment by odanoburu** [comment] 2019-08-15 20:32
because it's not a bug in sensetion, but you're right that it's not solved yet!

**Comment by arademaker** [comment] 2019-08-21 17:34
See the solution of pydelphin in https://github.com/delph-in/pydelphin/issues/250#issuecomment-523339258

**Comment by odanoburu** [comment] 2019-08-22 12:21
nice! and he also made a new release on pypi

**Closed by odanoburu** 2019-08-22 12:21 UTC
